### PR TITLE
[XCS-167] Migration for physical server details

### PR DESCRIPTION
**Pull request by walteraa**
This PR contains migrations to physical server asset details.

Notice: Some commits is comming from ManageIQ upstream.

### CODE REVIEW

**Comment by rodneyhbrown7** [comment]
I'm confused about this request, there are number of commits in here that don't apply to the request. I am wondering if it is because the development branch is behind the upstream branch.

**Comment by walteraa** [comment]
Yes, Development branch is out of date from upstream. Before Send this PR, I updated the XCS branch from upstream.

**Comment by juliancheal** [comment]
@walteraa I think it's best if we close this PR. If there is anything in it that hasn't been addressed by another PR then we should extract it and create a new one.

**Comment by walteraa** [comment]
Ok @juliancheal

**Pull request closed without merging**
